CREATE TYPE "user_role" AS ENUM (
  'user',
  'moderator',
  'admin'
);

CREATE TYPE "library_status" AS ENUM (
  'watching',
  'completed',
  'on_hold',
  'dropped',
  'plan_to_watch'
);

CREATE TYPE "notif_type" AS ENUM (
  'friend_request',
  'like_post',
  'comment_reply',
  'mention'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "birthdate" date NOT NULL,
  "localisation" varchar(255),
  "bio" text,
  "avatar_url" varchar(255),
  "banner_url" varchar(255),
  "role" user_role DEFAULT 'user',
  "theme_preference" varchar(20) DEFAULT 'light',
  "created_at" timestamp DEFAULT (now()),
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "User_Anime_Library" (
  "user_id" int,
  "anime_id" int,
  "status" library_status NOT NULL,
  "progress" int DEFAULT 0,
  "rewatch_count" int DEFAULT 0,
  "score" int,
  "is_private" boolean DEFAULT false,
  "updated_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "anime_id")
);

CREATE TABLE "User_Manga_Library" (
  "user_id" int,
  "manga_id" int,
  "status" library_status NOT NULL,
  "progress" int DEFAULT 0,
  "reread_count" int DEFAULT 0,
  "score" int,
  "is_private" boolean DEFAULT false,
  "updated_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "manga_id")
);

CREATE TABLE "Friendships" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "requester_id" int,
  "addressee_id" int,
  "status" varchar(20),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "related_anime_id" int,
  "related_manga_id" int,
  "content" text NOT NULL,
  "image_urls" text[],
  "is_spoiler" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "post_id" int,
  "parent_id" int,
  "content" text NOT NULL,
  "is_spoiler" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "Likes" (
  "user_id" int,
  "post_id" int,
  "comment_id" int,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "post_id", "comment_id")
);

CREATE TABLE "Notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_id" int,
  "sender_id" int,
  "type" notif_type NOT NULL,
  "is_read" boolean DEFAULT false,
  "payload" jsonb,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "User_Anime_Library" ("user_id", "status");

CREATE UNIQUE INDEX ON "Friendships" ("requester_id", "addressee_id");

COMMENT ON COLUMN "User_Anime_Library"."anime_id" IS 'ID externe Kitsu';

COMMENT ON COLUMN "User_Manga_Library"."manga_id" IS 'ID externe Kitsu';

COMMENT ON COLUMN "Friendships"."status" IS 'pending, accepted, blocked';

COMMENT ON COLUMN "Comments"."parent_id" IS 'Si rempli, c''est une réponse à un autre com';

ALTER TABLE "User_Anime_Library" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "User_Manga_Library" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Friendships" ADD FOREIGN KEY ("requester_id") REFERENCES "Users" ("id");

ALTER TABLE "Friendships" ADD FOREIGN KEY ("addressee_id") REFERENCES "Users" ("id");

ALTER TABLE "Posts" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("post_id") REFERENCES "Posts" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("parent_id") REFERENCES "Comments" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("post_id") REFERENCES "Posts" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("comment_id") REFERENCES "Comments" ("id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("recipient_id") REFERENCES "Users" ("id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("sender_id") REFERENCES "Users" ("id");
